example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json
from mywatchlist.views import show_xml_by_id
from mywatchlist.views import show_json_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('change/<int:id>', change_status, name='change_status'),
    path('delete/<int:id>', delete_task, name='delete_task'),
    path('json/', show_json, name='show_json'),
    path('add/', create_json, name='create_json'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchlist(models.Model):
    title = models.CharField(max_length=255)
    release_date = models.CharField(max_length=225)
    watched = models.BooleanField()
    rating = models.IntegerField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null=True)
    title = models.CharField(max_length=225)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Alanna',
        'student_id': '2106639913'
    }

    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchlist
from django.http import HttpResponse
from django.core import serializers

def show_mywatchlist(request):
    count_watched = MyWatchlist.objects.filter(watched = True).count()
    count_unwatched = MyWatchlist.objects.filter(watched = False).count()

    if (count_watched) >= count_unwatched:
        display_text = "Selamat, kamu sudah banyak menonton!"
    else:
        display_text = "Wah, kamu masih sedikit menonton!"

    context = {
        'movie_list': MyWatchlist.objects.all(),
        'name_id': "Alanna (2106639913)",
        'display_text': display_text,
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = MyWatchlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")  

def show_json_by_id(request,id):
    data = MyWatchlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")   

    

todolist/views.py
import datetime
from django.shortcuts import render
from todolist.models import Task
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    user = request.user
    context = {
        "username" : user.username,
        "todolist" : Task.objects.filter(user=user),
    }
    return render(request, "todolist.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully registered!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Invalid username/password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def create_task(request):
    if request.method == "POST":
        task = request.POST

        Task.objects.create(
            user = request.user,
            date = datetime.datetime.now(),
            title = task.get("title"),
            description = task.get("description"),
            is_finished = False,
        )
        return HttpResponseRedirect(reverse('todolist:show_todolist'))
    return render(request, 'create_task.html')

def change_status(request, id):
    task = Task.objects.get(id = id)
    task.is_finished = not task.is_finished
    task.save()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

def delete_task(request, id):
    Task.objects.get(id = id).delete()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

def show_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_json(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task.objects.create(
            title = title, 
            description = description,
            date = datetime.date.today(), 
            is_finished = False, 
            user=request.user
            )

        result = {
            'id':task.id,
            'fields':{
                'title':task.title,
                'description':task.description,
                'is_finished':task.is_finished,
                'date':task.date,
            }
        }

        return JsonResponse(result)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{student_id}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_barang %}
    <tr>
        <td style='text-align:center; vertical-align:middle'>{{item.item_name}}</td>
        <td style='text-align:center; vertical-align:middle'>{{item.item_price}}</td>
        <td style='text-align:center; vertical-align:middle'>{{item.item_stock}}</td>
        <td style='text-align:center; vertical-align:middle'>{{item.rating}}</td>
        <td style='text-align:center; vertical-align:middle'>{{item.description}}</td>
        <td style='text-align:center; vertical-align:middle'> <a href={{item.item_url}}> {{item.item_url}}</a></td>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style="font-family:system-ui">My Watchlist</h1>
  <h3 style="font-family:system-ui">By: {{name_id}}</h3>
  <h2 style="font-family:system-ui">{{display_text}}</h2>
  
  <table style="width:100%; font-family:system-ui">
    <tr style="font-size:140%;">
      <th>Title</th>
      <th>Release Date</th>
      <th>Watched</th>
      <th>Rating</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in movie_list %}
    <tr style='text-align:center; vertical-align:middle'>
        <td>{{item.title}}</td>
        <td>{{item.release_date}}</td>
        <td>{{item.watched}}</td>
        <td>{{item.rating}}</td>
        <td style='width:50%'>{{item.review}}</td>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create new task | Todolist</title>
{% endblock meta %}

{% block content %}
<style>
    * {
        font-family: system-ui;
    }
    h1 {
        text-align: center; 
        vertical-align: middle
    }
    form {
        margin: auto;
        width: 400px;
        padding: 1em;
        border: 1px solid #ccc;
        border-radius: 1em;
    }
</style>
<div class = "create-task">

    <h1>✍🏼 Create New Task</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Task Title: </td>
                <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><textarea type="text" name="description" placeholder="Description" class="form-control"></textarea></td>
            </tr>

            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Create Task"/></td>  
            </tr>
        </table>
    </form>

</div>

{% endblock content %}

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create new task | Todolist</title>
{% endblock meta %}

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">
<style>
  * {
    font-family: "Work Sans";
    text-align:center;
    vertical-align: middle;
    color: #2e3c4d;
  }
  td, input, textarea {
    text-align: left; 
  }
  form {
    border-radius:0.5em; 
    box-shadow: 0px 0px 7px rgba(128, 128, 128, 0.211);   
    background-color: rgba(178, 178, 178, 0.211);   
    margin: auto;
    width: 270px;
    padding: 1em;
    border-radius: 1em;
  }
  h1 {
    color:#413f76;
  }
  body {
    background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
  }
  .create-task {
    padding-top:10%;
    padding-bottom: 20%;
  }
  .logout {
    background-color: rgba(255, 255, 255, 0.112); 
    border-color: rgba(255, 255, 255, 0.112); 
    box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.3);
    color: #2e3c4d;
  } 
    
  .submit {
    margin-top: 0.5em;
    border-radius: 0.5em;
    font-weight: 1000;
    color:rgba(255, 255, 255, 0.966);
    background-color:#5755a2;
    border-color: transparent;
    box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.3);
  }
</style>

<nav class="navbar navbar-expand-lg">
   <div class="container-fluid">
      <a></a>
      <a class="btn btn-primary logout" href="{% url 'todolist:logout' %}">Logout</a>
    </div>
</nav>

<div class = "create-task">
    <h1>✍🏼 Create New Task</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Task Title: </td>
                <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><textarea type="text" name="description" placeholder="Description" class="form-control"></textarea></td>
            </tr>

            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Create Task" class="submit"/></td>  
            </tr>
        </table>
    </form>

</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}

<title>Login | Todolist</title>
{% endblock meta %}

{% block content %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">
<style>
  * {
    font-family: "Work Sans";
    text-align:center;
    vertical-align: middle;
    color: #2e3c4d;
  }
  td, input {
    text-align: left; 
  }
  form {
    border-radius:0.5em; 
    box-shadow: 0px 0px 7px rgba(128, 128, 128, 0.211);   
    background-color: rgba(178, 178, 178, 0.211);   
    margin: auto;
    width: 270px;
    padding: 1em;
    border-radius: 1em;
  }
  h1, a, a.visited {
    color:#413f76;
  }
  body {
    background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
  }
  .login {
    padding: 10%;
  }
</style>

<div class="login">
  <h1>Login</h1>
    <form method="POST" action="">
      {% csrf_token %}
      <table>
        <tr>
          <td>Username: </td>
          <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
        </tr>
                    
        <tr>
          <td>Password: </td>
          <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
        </tr>

        <tr>
          <td></td>
          <td><input class="btn login_btn" type="submit" value="Login"></td>
        </tr>
      </table>
    </form>

  {% if messages %}
    <ul>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  </br>
  <p>Don't have an account yet? <a href="{% url 'todolist:register' %}">Register</a></p>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register | Todolist</title>
{% endblock meta %}

{% block content %}  

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">

<style>
  * {
    font-family: "Work Sans";
    text-align: left; 
    vertical-align:text-top;
  }
  h1 {
    text-align: center;
    color:#413f76;
    padding-bottom:3%;
  }
  th {
    font-size:20px;
  }
  @media screen and (max-width: 490px) {
    h1 {
      font-size:7vw;
    }
    th {
      font-size:4vw;
    }
    td {
      font-size:3vw;
    }
  }

  body {
    background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
  }  
  form {
    margin:auto; 
    width: 70%; 
    padding: 1%; 
    border-radius: 1em; 
    font-size: small; 
    background-color: rgba(204, 204, 204, 0.277); 
    box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.211); 
  }
  .register {
    padding-top: 5%;
    padding-bottom: 10%;
  }
  .login {
    background-color: rgba(37, 0, 110, 0.554); 
    border-color: transparent; 
    box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.3);
    color: white;
  }
</style>

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a></a>
    <a class="btn btn-primary login" href="{% url 'todolist:login' %}">Login</a>
  </div>
</nav>

<div class="register">
    
  <h1>Create new account</h1>  
    <form method="POST"" >  
      {% csrf_token %}  
      <table>  
        {{ form.as_table }}  
        <td></td>
        <td><input style="font-size:medium;" type="submit" name="submit" value="Register"/></td>  
      </table>  
    </form>
      
  {% if messages %}  
    <ul>   
      {% for message in messages %}  
        <li>{{ message }}</li>  
      {% endfor %}  
    </ul>   
  {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>Todolist</title>
{% endblock meta %}

{% block content %}
<!doctype html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $.get("/todolist/json/", function(data) {
            for (i=0; i<data.length; i++){
                $("#todolist").append(`
                <div id="${data[i].id}--task" class="col-md-6 col-lg-3 mb-3">
                    <div class="card d-flex">
                      <div class="card-body d-flex flex-column">
                        <h5 class="card-title">${data[i].fields.title}</h5>
                        <p class="card-text mb-1 date">${data[i].fields.date}</p>
                        <p class="card-text">${data[i].fields.description}</p>
                        <div class="mt-auto">
                          <a href="/todolist/delete/${data[i].pk}" class="btn btn-primary delete mb-2">Delete</a>
                          ${data[i].fields.is_finished ?
                            `<a href="/todolist/change/${data[i].pk}" class="btn btn-primary done mb-2">Done</a>` :
                            `<a href="/todolist/change/${data[i].pk}" class="btn btn-primary todo mb-2">To Do</a>`}
                        </div>
                      </div>
                    </div>
                </div>`)
            }
        });


        $("#submit_btn").click(function(){
          $.post("/todolist/add/", {
            title: $("#title").val(),
            description: $("#description").val()
          },
          function(result, status){
                if (status == 'success') {
                $("#todolist").append(`
                <div id="${result.id}--task" class="col-md-6 col-lg-3 mb-3">
                      <div class="card">
                        <div class="card-body d-flex flex-column">
                          <h5 class="card-title">${result.fields.title}</h5>
                          <p class="card-text mb-1 date">${result.fields.date}</p>
                          <p class="card-text">${result.fields.description}</p>
                          <div class="mt-auto">
                            <a href="/todolist/delete/${result.id}" class="btn btn-primary delete mb-2" >Delete</a>
                            ${result.fields.is_finished ?
                              `<a href="/todolist/change/${result.id}" class="btn btn-primary done mb-2">Done</a>` :
                              `<a href="/todolist/change/${result.id}" class="btn btn-primary todo mb-2">To Do</a>`}
                          </div>
                        </div>
                      </div>
                  </div>`);
                $('#title').val('')
                $('#description').val('')
                }
            }
          )
        })
    });
    
</script>

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">
<style>
  * {
    font-family: "Work Sans";
    color: #2e3c4d;
    text-align: center;
  }
  h1 {
    color:#413f76;
  }
  body {
    background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
  }
  .card {
    background-color: rgba(255, 255, 255, 0.2); 
    box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.211); 
    backdrop-filter: blur(30px);
    border-radius: 1em;
    transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
    cursor: pointer;
  }
  .card:hover{
    transform: scale(1.03);
    box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
  }
  .card-title {
    font-family: system-ui;
    font-weight: bold;
  }
  .card-text {
    font-family: system-ui;
    font-size: 90%;
  }
  .done {
    background-color: rgba(37, 165, 97, 0.35);
    border-color: transparent;
  }
  .todo {
    background-color: rgba(212, 56, 56, 0.38);
    border-color: transparent;
    font-weight: 900;
  }
  .create {
    font-weight: 1000;
    color:rgba(255, 255, 255, 0.966);
    background-color: #767ae4be;
    border-color: transparent;
    box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.3);

  }
  .date {
    font-size: small;
    color: #2e3c4d;
  }
  .logout {
    background-color: rgba(255, 255, 255, 0.112); 
    border-color: rgba(255, 255, 255, 0.112); 
    box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.3);
    color: #2e3c4d;
  } 
  .delete {
    background-color:#0000002d;
    border-color:transparent;
  }
  .card-footer {
    background: transparent;
    border:0px;
  }
  .container {
    padding-left: 7%;
    padding-right: 7%;
    padding-bottom: 7%
  }
  .modal-background-color {
    border-color: transparent;
    width: 300px;
    padding: 1em;
  }
</style>

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">👋🏼 Hello, {{ username }}!</a>
    <a class="btn btn-primary logout" href="{% url 'todolist:logout' %}">Logout</a>
  </div>
</nav>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<div style="padding-top: 1%; padding-bottom: 3%;">
  <h1>To-Do List</h1>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary mb-5 create" data-bs-toggle="modal" data-bs-target="#createTaskModal" data-bs-whatever="@mdo">
  + Add Task
</button>

<!-- Modal -->
<div class="modal" id="createTaskModal" tabindex="-1" aria-labelledby="createTaskModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-background-color">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="createTaskModalLabel">Add new task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
      </div>
      <div class="modal-body" style="text-align:left;">
        {% csrf_token %}
        <label>Task Title:</label><br>
        <input id="title" class="appearance-none border rounded py-2 px-3 mx-1 text-zinc-800" type="text" name="title" placeholder="Title"><br>
        <label>Description:</label><br>
        <input id="description" class="appearance-none border rounded py-2 px-3 mx-1 text-zinc-800" type="description" name="description" placeholder="Task Description">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button id="submit_btn" type="button" class="btn btn-primary create" id="add-task" data-bs-dismiss="modal">Add</button>
      </div>
    </div>
  </div>
</div>
</body>

<div class="row m-2" id="todolist"></div>


 {% endblock content %}